name: "ESP Host Bridge"
version: "2026.03.21.02"
slug: "esp_host_bridge"
description: "USB CDC bridge and host telemetry web UI for ESP display devices."
url: "https://github.com/rog713/ESP-Host-Bridge"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
ingress: true
ingress_port: 8654
panel_icon: "mdi:monitor-dashboard"
panel_title: "ESP Host Bridge"
# host_network: true
# host_uts: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
udev: true
uart: true
full_access: false
apparmor: true
webui: "http://[HOST]:[PORT:8654]"
watchdog: "http://[HOST]:[PORT:8654]/api/status"
options: {}
schema: {}
